### ISSUE TITLE
Use sensors_plus instead of flutter_compass

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [Xennis/flutter_map_location#81]
The sensors_plus package is of much better code quality, has more maintainers and - in opposite to flutter_compas - compatible with Flutter's 2nd version of Android embedding.

I would recommend to use sensors_plus instead of flutter_compass.

**Comment by Xennis** [comment]
https://pub.dev/packages/sensors_plus/

It's maintained by fluttercommunity.dev nice. Looks pretty good. If someone is interested in creating a PR I would accept it.

**Comment by comatory** [comment]
I'm getting deprecated warnings because of `flutter_compass`.

**Comment by comatory** [comment]
Wouldn't this be fixed by upgrading to `flutter_compass ^0.7.0`? Seems like they already dealt with the deprecated Android API problem: https://github.com/hemanthrajv/flutter_compass/issues/62

**Comment by xni06** [comment]
> Wouldn't this be fixed by upgrading to `flutter_compass ^0.7.0`? Seems like they already dealt with the deprecated Android API problem: [hemanthrajv/flutter_compass#62](https://github.com/hemanthrajv/flutter_compass/issues/62)

I've created a PR for this - https://github.com/Xennis/flutter_map_location/pull/84

In the meantime, you could use the following:

```
  flutter_map_location:
    git:
      url: https://github.com/xni06/flutter_map_location.git
      ref: feature/update-fluter-compass
```

**Comment by lume-code** [comment]
@xni06 If you could possibly raise the `flutter_map` dependency version to 0.14.0 as well.

**Comment by xni06** [comment]
> @xni06 If you could possibly raise the `flutter_map` dependency version to 0.14.0 as well.

That's not my repo but you can use my fork if you like:

```
  flutter_map:
    git:
      url: https://github.com/xni06/flutter_map.git
      ref: feature/add-marker-data-property
```
